### ISSUE TITLE
WvW KDR stat not shown if "hide stats with value = 0" is enabled

### ISSUE THREAD

**Issue by hjbotha** [Taschenbuch/BlishHud-SessionTracker#1]
The WvW KDR stat is not shown if "hide stats with value = 0" is enabled, even if there are kills and deaths > 0.

Version 1.1.2

**Comment by Taschenbuch** [comment]
Hm, yeah. Could be bugged because all other stats are integers while KDR is a floating point number.
But the module is not developed any further for now because i stopped playing GW2.

**Comment by Taschenbuch** [comment]
fixed in 2.x.x
