### ISSUE TITLE
Tracking Silverwaste shovels

### ISSUE THREAD

**Issue by Charybdis** [Taschenbuch/BlishHud-SessionTracker#6]
As per title. Silverwaste shovels are used in guild hall levelling and, for me at least, have been a very specific reason to go to that map recently.

Would probably fit under General->Misc and/or PvE->Open World.

Thanks for listening.

**Comment by Taschenbuch** [comment]
Added silverwastes shovels under General/Misc.
Should be available after next blish restart or after disabling and enabling the module again. No module version or blish version update is required.
